joy_teleop:
  ros__parameters:

    pilot:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel
      deadman_buttons: [5] # RT
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.4
          offset: 0.0
        angular-z:
          axis: 0
          scale: 2.5

    dock:
      type: topic
      interface_type: std_msgs/msg/Empty
      topic_name: dock
      deadman_buttons: [3] # Y
      message_value: []

    undock:
      type: topic
      interface_type: std_msgs/msg/Empty
      topic_name: undock
      deadman_buttons: [1] # B
      message_value: []
