joy_teleop:
  ros__parameters:

    pilot:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel
      deadman_buttons: [5] # RT
      axis_mappings:
        linear-x:
          axis: 4 # right stick UpDown
          scale: 0.4
          offset: 0.0
        angular-z: # left stick LeftRight
          axis: 0
          scale: 2.5

    dock:
      type: topic
      interface_type: std_msgs/msg/Empty
      topic_name: dock
      deadman_buttons: [3, 5] # Y + RT
      match: all
      message_value: []

    undock:
      type: topic
      interface_type: std_msgs/msg/Empty
      topic_name: undock
      deadman_buttons: [1, 5] # B + RT
      match: all
      message_value: []

    motor_on:
      type: topic
      interface_type: ca_msgs/msg/Motor
      topic_name: motor
      deadman_buttons: [5] # RT
      axis_mappings:
        main_brush:
          axis: 2
          scale: -0.5
          offset: 0.5
        side_brush:
          axis: 2
          scale: -0.5
          offset: 0.5
        vacuum:
          axis: 2
          scale: -0.5
          offset: 0.5
